---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de automatización de ONTAP
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Notas de la versión
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: Opciones de automatización de ONTAP
      url: "/get-started/ontap_automation_options.html"
    - title: Su primera llamada API
      url: "/get-started/first_call.html"
  - title: API REST de ONTAP
    links:
    - title: Detalles de implementación de REST
      url: "/rest/rest_web_services_foundation.html"
    - title: Consideraciones adicionales
      url: "/rest/object_references_and_access.html"
    - title: Resumen de recursos REST
      url: "/resources/overview_categories.html"
    - title: Referencia de API
      url: "/reference/api_reference.html"
  - title: Automatización
    links:
    - title: Biblioteca de clientes de Python
      url: "/python/overview_pcl.html"
    - title: ONTAP y Ansible
      url: "/automate/ontap_ansible.html"
    - title: Blogs de automatización
      url: "/automate/blogs.html"
  - title: Migrar a la API DE REST
    links:
    - title: Inhabilitación de ONTAPI
      url: "/migrate/overview.html"
    - title: Asignación de ONTAP A REST
      url: "/migrate/mapping.html"
    - title: Contadores de rendimiento
      url: "/migrate/performance-counters.html"
    - title: Artículos de blog
      url: "/migrate/blogs.html"
  - title: Conocimiento y apoyo
    links:
    - title: Recursos adicionales
      url: "/additional/resources.html"
    - title: DevNet de NetApp
      url: https://devnet.netapp.com/restapi.php
    - title: Documentos de ONTAP 9
      url: https://docs.netapp.com/us-en/ontap/
    - title: Documentos de ONTAP Select
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Documentación de productos All ONTAP
