---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de automatización de ONTAP
    url: "/index.html"
  - title: Novedades
    entries:
    - title: "¿Qué novedades tiene la API de REST DE ONTAP"
      url: "/whats-new.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: Avisos legales
    url: "/legal-notices.html"
