---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: Cada versión de ONTAP actualiza la API de REST DE ONTAP para incorporar nuevas funciones, mejoras y correcciones de errores. 
---
= Novedades de la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cada versión de ONTAP actualiza la API de REST DE ONTAP para incorporar nuevas funciones, mejoras y correcciones de errores.


TIP: Debe revisar el https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP"^] para obtener información adicional, incluidas las limitaciones o los problemas conocidos. Consulte link:api-changes.html["Cambios en las llamadas de la API DE REST DE ONTAP"] también si hay cambios que puedan afectar a su software de automatización.



== ONTAP 9.18.1

La versión ONTAP 9.18.1 continúa ampliando las capacidades de la API REST de ONTAP con once nuevas llamadas a la API. Las mejoras se centran principalmente en la seguridad, pero también incluyen una mejora relacionada con la administración del almacenamiento.

Seguridad:: Hay dos mejoras de seguridad importantes introducidas con la API REST de ONTAP 9.18.1. Puede utilizar los nuevos puntos de conexión de la API de red del clúster para visualizar y actualizar la configuración de seguridad de la red del clúster. Se incluye un soporte robusto para la gestión de certificados con la red del clúster. Además, puede visualizar y actualizar la configuración de seguridad de la red HA para el tráfico NVLog.
Reducida:: NetApp FlexCache es una caché persistente de un volumen de origen. Admite la función fan-out, de modo que se puede crear más de un FlexCache a partir de un único volumen de origen. La API REST incluye soporte para la recuperación del estado de la conexión entre las instancias de caché y los volúmenes de origen.




== ONTAP 9.17.1

La versión 9.17.1 de ONTAP continúa ampliando las capacidades de la API REST de ONTAP con casi dos docenas de nuevas llamadas a la API. Esta versión se centra principalmente en mejoras de seguridad con actualizaciones adicionales para el procesamiento de mediadores, los subsistemas NMVe y los contenedores de aplicaciones.

Seguridad:: La API REST de ONTAP 9.17.1 incorpora cuatro funciones de seguridad principales. La elevación de privilegios JIT (Just-in-Time) de ONTAP es una mejora del control de acceso basado en roles (RBAC). Los administradores de clústeres pueden solicitar la elevación temporal a un rol existente, lo que permite el acceso a comandos privilegiados. Esta función incluye un conjunto completo de opciones de configuración. Se ha añadido compatibilidad con el administrador de claves Barbican de OpenStack. Este KMS se utiliza para mantener las claves de NetApp Volume Encryption (NVE). La protección autónoma contra ransomware (ARP) para volúmenes SAN se incluye en ONTAP 9.17.1. Las estadísticas detalladas de entropía de ARP están disponibles a través de la API REST. También se han añadido varias llamadas a la API para gestionar la configuración predeterminada de metadatos SAML de un clúster.
Mediadores de clúster:: Puede hacer ping al servicio en la nube de la consola de NetApp mediante la API REST de ONTAP . También puede modificar la configuración de un mediador específico mediante el método PATCH con un endpoint existente.
NVMe:: Los subsistemas NVMe mantienen el estado de configuración y el control de acceso al espacio de nombres para un conjunto de hosts conectados a NVMe. Con ONTAP 9.17.1, puede modificar un subsistema NVMe mediante el método PATCH con un endpoint existente.
Contenedores de aplicaciones:: Los contenedores de aplicaciones son una novedad de ONTAP 9.17.1 y permiten el aprovisionamiento de uno o más objetos de almacenamiento. Puede configurar las políticas y reglas necesarias para el acceso de los clientes al almacenamiento. También se pueden aprovisionar volúmenes FlexCache .




== ONTAP 9.16.1

ONTAP 9.16,1 incluye más de dos docenas de nuevas llamadas a la API que continúan ampliando las capacidades de la API REST DE ONTAP. Estas mejoras se centran principalmente en la seguridad, pero también incluyen mejoras con las métricas y la administración de bloques.


NOTE: La API de REST DE ONTAP expuesta a los usuarios de los sistemas NetApp ASA R2 (ASA A1K, ASA A70 y ASA A90) es diferente de la API DE REST del resto de sistemas FAS, AFF y ASA. Consulte https://docs.netapp.com/us-en/asa-r2/learn-more/rest-api-support.html["Soporte de API DE REST para los sistemas ASA R2"^] para obtener más información.

Compatibilidad con OAuth 2,0 para Microsoft Entra ID:: El soporte OAuth 2,0 se introdujo por primera vez con ONTAP 9.14,1. Las capacidades de OAuth 2,0 se han mejorado con ONTAP 9.16,1 para admitir el servidor de autorización de Microsoft Entra ID (anteriormente Azure AD) con las afirmaciones estándar de OAuth 2,0. Dos características principales se incluyen como se describe a continuación.
OAuth 2,0 con grupos como UUIDs:: Las reclamaciones de grupo estándar Entra ID basadas en valores de estilo UUID se admiten a través de dos nuevas capacidades con diez nuevas llamadas API:
+
--
* UUID de grupo a asignación de nombre de grupo (`/security/groups`)
* Grupo UUID a asignación de roles (`/security/group/role-mapping`)


--
OAuth 2,0 con roles externos:: Un rol externo se define en un proveedor de identificación de OAUTH 2,0 definido en ONTAP. Es posible crear y administrar relaciones de asignación entre estos roles externos y los roles de ONTAP. Se han agregado cinco nuevas llamadas a la API.
Autenticación web:: La autenticación web (WebAuthn) es un estándar web para autenticar usuarios de forma segura basado en la criptografía de clave pública. Con ONTAP, es compatible con la administración de MFA resistentes a phishing a través del Administrador del sistema y la API REST DE ONTAP. Se han agregado siete nuevas llamadas API en varios extremos.
Versiones y actualizaciones autónomas de la Protección contra ransomware:: Se han agregado dos llamadas a la API con un nuevo extremo para gestionar el paquete autónomo de protección contra ransomware que utiliza ONTAP. Puede mostrar la versión y actualizar el paquete Autonomous Ransomware Protection.
Métricas de qtree:: ONTAP 9.16,1 incluye una función opcional de supervisión del rendimiento ampliado para qtrees. Con la función habilitada, ONTAP captura datos adicionales, incluidas métricas de latencia y datos históricos. Se ha agregado un nuevo punto final para permitirle recuperar estos datos de rendimiento.
S3 instantáneas en bloque:: Se han agregado cuatro nuevas llamadas API para permitirle crear y administrar instantáneas de sus buckets S3. Cada snapshot es una imagen del bucket tal como existía cuando se creó la snapshot.




== ONTAP 9.15.1

ONTAP 9.15,1 continúa expandiendo las funcionalidades de la API REST DE ONTAP, incluida la compatibilidad con dos funciones nuevas.

NFS sobre TLS:: Hay tres nuevos puntos finales disponibles con esta función. Puede emitir estas llamadas API para recuperar todas las interfaces de NFS sobre TLS, recuperar una interfaz específica mediante UUID y actualizar las propiedades de configuración de una interfaz TLS. Colectivamente, estas llamadas API proporcionan un equivalente al conjunto de `vserver nfs tls interface` Comandos de la CLI.



CAUTION: NFS con TLS está disponible en ONTAP 9.15.1 como versión preliminar pública. Como oferta de vista previa, esta función no se admite para cargas de trabajo de producción con ONTAP 9.15.1.

Aplicaciones de backup de Windows y symlinks de tipo Unix:: Cuando una aplicación de copia de seguridad de Windows encuentra un enlace simbólico de estilo Unix (symlink), el enlace se atraviesa y ONTAP devuelve los datos y se realiza una copia de seguridad. A partir de ONTAP 9.15.1, también tiene la opción de hacer una copia de seguridad del symlink en lugar de los datos a los que apunta. Esto puede ofrecer varios beneficios, como un mejor rendimiento de sus aplicaciones de backup. El punto final `/protocols/cifs/services/{svm.uuid}` se ha actualizado para incluir el nuevo parámetro `backup-symlink-enabled` en el `options` objeto.




== ONTAP 9.14.1

La versión ONTAP 9.14.1 incluye más de tres docenas de nuevas llamadas a la API que siguen ampliando las funcionalidades de la API DE REST DE ONTAP. Estos extremos admiten varias características nuevas de ONTAP, así como actualizaciones de las características existentes. Esta versión se centra principalmente en las mejoras de seguridad, pero también incluye mejoras en NAS, CALIDAD DE SERVICIO y métricas de rendimiento.

Seguridad:: Hay dos funciones de seguridad principales que se han introducido con ONTAP 9.14.1. La autorización abierta (OAuth 2,0) es un marco basado en tokens que se puede utilizar para restringir el acceso a sus recursos de almacenamiento de ONTAP. Puede usarlo con clientes que acceden a ONTAP a través de la API DE REST. La configuración se puede realizar con cualquiera de las interfaces administrativas de ONTAP, incluida la API de REST. La versión ONTAP 9.14.1 también incluye soporte para Cisco Duo, que proporciona autenticación de dos factores para inicios de sesión SSH. Puede configurar Duo para que funcione a nivel de clúster de ONTAP o SVM. Además de estas dos nuevas características, se han agregado varios puntos finales para mejorar el control sobre sus almacenes de claves.
Almacenamiento persistente de FPolicy:: FPolicy proporciona una plataforma para la gestión de políticas de ONTAP. Proporciona un contenedor para los distintos componentes o elementos, como eventos y el motor de políticas. Ahora es posible usar la API de REST para configurar y administrar un almacén persistente de la configuración y los eventos de ONTAP FPolicy. Cada SVM puede tener un almacén persistente que se comparte para las diversas políticas dentro de la SVM.
Opciones de CALIDAD DE servicio:: Se han introducido dos extremos para permitirle recuperar y establecer opciones de QOS para el clúster. Por ejemplo, puede reservar un porcentaje de los recursos de procesamiento del sistema disponibles para las tareas en segundo plano.
Métricas de rendimiento:: ONTAP mantiene información estadística sobre las características operativas del sistema. Esta información se presenta en un formato de base de datos que consta de tablas y filas. Con ONTAP 9.14.1, se añaden más datos de métricas en varias categorías de recursos, como Fibre Channel, iSCSI, LUN y NVME. Estos datos de métricas adicionales siguen acercando la API DE REST DE ONTAP a la paridad con la API de Data ONTAP (ONTAPI o ZAPI).
Otras mejoras:: Existen varias mejoras adicionales que pueden ser útiles dependiendo de su entorno. Estos nuevos extremos mejoran el acceso a los iniciadores SAN y controlan la configuración de la caché del host, además de permitir el acceso a mensajes AutoSupport individuales.




== ONTAP 9.13.1

ONTAP 9.13.1 continúa ampliando las funcionalidades de la API DE REST DE ONTAP con más de dos docenas de nuevas llamadas a la API. Estos extremos admiten las nuevas funciones de ONTAP, así como mejoras en las funciones existentes. Esta versión se centra en mejoras en la seguridad, la gestión de recursos, las opciones de configuración de SVM mejoradas y las métricas de rendimiento.

Etiquetado de recursos:: Puede usar etiquetas para agrupar los recursos de la API DE REST. Puede hacerlo para asociar recursos relacionados dentro de un proyecto o grupo organizativo específico. El uso de etiquetas puede ayudar a organizar y realizar un seguimiento de los recursos de manera más eficaz.
Grupos de consistencia:: ONTAP 9.13.1 continúa ampliando la disponibilidad de los datos de contador de rendimiento. Ahora puede acceder a este tipo de información estadística para realizar un seguimiento del rendimiento histórico y la capacidad para los grupos de coherencia. Además, se han incluido mejoras que permiten configurar y gestionar las relaciones primario-secundario entre grupos de coherencia.
Configuración de DNS por SVM:: Los extremos DNS existentes se han ampliado para permitir que se realice la configuración de servidor y dominio DNS para SVM individuales.
Configuración de roles EMS:: La función de soporte EMS existente se ha ampliado para permitir la gestión de roles y la configuración de control de acceso asignada a los roles. Esto proporciona la capacidad de limitar o filtrar los eventos y mensajes según la configuración del rol.
Seguridad:: Es posible usar la API de REST para configurar los perfiles de contraseña de un solo uso (TOTP) basados en tiempo para las cuentas que inician sesión y acceden a ONTAP mediante SSH. Además, los extremos del gestor de claves se han ampliado para proporcionar una operación de restauración desde un servidor de gestión de claves especificado.
Configuración de CIFS por SVM:: Los extremos de CIFS existentes se han expandido para permitir actualizar la configuración de un SVM específico.
Reglas de bloques de S3:: Los S3 puntos finales de bloque existentes se han ampliado para incluir una definición de regla. Cada regla es una lista de objetos y define el conjunto de acciones que se van a realizar en un objeto dentro del depósito. Colectivamente, estas reglas le permiten administrar mejor el ciclo de vida de sus cubos S3.




== ONTAP 9.12.1

ONTAP 9.12.1 sigue ampliando las capacidades de la API REST de ONTAP con más de cuarenta nuevas llamadas API. Estos extremos admiten las nuevas funciones de ONTAP, así como mejoras en las funciones existentes. Esta versión se centra en las mejoras en la seguridad y las funciones NAS.

Mejoras de seguridad:: Amazon Web Services incluye un servicio de gestión de claves que proporciona almacenamiento seguro para claves y otros secretos. Puede acceder a este servicio a través de la API DE REST para permitir que ONTAP almacene sus claves de cifrado de forma segura en el cloud. Además, puede crear y enumerar las claves de autenticación usadas con el cifrado del almacenamiento de NetApp.
Active Directory:: Es posible gestionar las cuentas de Active Directory definidas para un clúster de ONTAP. Esto incluye la creación de cuentas nuevas, así como la visualización, actualización y eliminación de cuentas.
Políticas de grupos CIFS:: Se ha mejorado la API REST para admitir la creación y gestión de políticas de grupos CIFS. La información de configuración se encuentra disponible y se administra mediante objetos de política de grupo que se aplican a todas las SVM o a determinadas.




== ONTAP 9.11.1

ONTAP 9.11.1 sigue ampliando las funcionalidades de la API DE REST de ONTAP con casi cien llamadas nuevas al API. Estos extremos admiten las nuevas funciones de ONTAP, así como mejoras en las funciones existentes.

RBAC granular:: La funcionalidad de control de acceso basado en roles (RBAC) de ONTAP se ha mejorado para proporcionar granularidad adicional. Puede usar los roles tradicionales o crear roles personalizados nuevos según sea necesario mediante la API DE REST. Cada rol se asocia con uno o más privilegios, cada uno de los cuales identifica una llamada de API DE REST o un comando de la CLI junto con el nivel de acceso. Hay nuevos niveles de acceso disponibles para roles DE REST como `read_create` y.. `read_modify`. Esta mejora se basa en la paridad con la API de Data ONTAP (ONAPI o ZAPI) y permite la migración de clientes a la API DE REST. Consulte link:rest/rbac_overview.html["Seguridad RBAC"] si quiere más información.
Contadores de rendimiento:: En versiones anteriores de ONTAP se había mantenido información estadística sobre las características de funcionamiento del sistema. Con el lanzamiento de la versión 9.11.1, esta información se ha mejorado y ahora está disponible a través de la API DE REST. Un administrador o un proceso automatizado pueden acceder a los datos para determinar el rendimiento del sistema. La información estadística, tal como la mantiene el subsistema counter Manager, se presenta en formato de base de datos utilizando tablas y filas. Con esta mejora, la API REST de ONTAP se acerca más a la paridad con la API de Data ONTAP (ONAPI o ZAPI).
Gestión de agregados:: Se ha mejorado la gestión de los agregados de almacenamiento de ONTAP. Se pueden usar los extremos DE REST actualizados para mover agregados en línea y sin conexión, así como para gestionar los repuestos.
Capacidad de subred IP:: La capacidad de redes ONTAP se ha ampliado para incluir la compatibilidad con las subredes IP. La API REST proporciona acceso a la configuración y la gestión de las subredes IP dentro de un clúster de ONTAP.
Verificación de varios administradores:: La función de verificación de varios administradores proporciona un marco de autorización flexible para proteger el acceso a comandos u operaciones de ONTAP. Puede definir reglas que identifiquen los comandos restringidos. Cuando un usuario solicita acceso a un comando específico, varios administradores de ONTAP pueden otorgar la aprobación según corresponda.
Mejoras de SnapMirror:: La funcionalidad SnapMirror se ha mejorado en varias áreas, incluida la programación. La paridad de la relación de SnapVault se agregó en una relación de DP con ONTAP 9.11.1 también, la función del acelerador disponible con la API DE REST ha alcanzado la paridad con la API de Data ONTAP (ONAPI o ZAPI). En relación con este hecho, existe soporte para crear y gestionar copias snapshot masivas.
Pools de almacenamiento:: Se añadieron varios extremos para proporcionar acceso a los pools de almacenamiento de ONTAP. Se incluye soporte para crear y enumerar los pools de almacenamiento en un clúster, así como actualizar y eliminar pools específicos por ID.
Compatibilidad con la caché de servicios de nombres:: Se han mejorado los servicios de nombres de ONTAP para admitir el almacenamiento en caché, lo que mejora el rendimiento y la resiliencia. Ahora se puede acceder a la configuración de la caché de servicios de nombres a través de la API DE REST. La configuración se puede aplicar en varios niveles, incluidos hosts, usuarios unix, grupos unix y grupos de red.
Herramienta de generación de informes ONTAAPI:: La herramienta de creación de informes ONTAPI ayuda a los clientes y partners a identificar el uso que ONTAPI hace en su entorno. Esta herramienta proporciona información valiosa para los clientes que planifican la migración de ONTAPI a la API DE REST DE ONTAP.




== ONTAP 9.10.1

ONTAP 9.10.1 sigue ampliando las funcionalidades de la API DE REST de ONTAP. Se han añadido más de un centenar de extremos nuevos para admitir nuevas funciones de ONTAP y mejoras en las funciones existentes. A continuación se presenta un resumen de las mejoras de la API DE REST.

Grupo de consistencia de aplicaciones:: Un grupo de coherencia es un conjunto de volúmenes que se agrupan cuando se ejecutan ciertas operaciones, como una Snapshot. Esta función extiende la misma coherencia de bloqueo e integridad de datos implícita con operaciones de un único volumen en un conjunto de volúmenes. Es valioso para aplicaciones de carga de trabajo de varios volúmenes de gran tamaño.
Migración de SVM:: Puede migrar una SVM desde un clúster de origen a un clúster de destino. Los nuevos extremos proporcionan un control completo, incluida la capacidad de pausar, reanudar, recuperar estado y cancelar una operación de migración.
Clonado y gestión de archivos:: Se ha mejorado la gestión y el clonado de archivos en el nivel de volumen. Los nuevos extremos DE REST admiten operaciones de movimiento, copia y división de archivos.
Auditoría de S3 mejorada:: La auditoría de los eventos de S3 es una mejora de seguridad que le permite realizar un seguimiento y registrar ciertos eventos de S3. Se puede establecer un selector de eventos de auditoría de S3 por bloque y por SVM.
Defensa contra ransomware:: ONTAP detecta archivos que potencialmente contienen una amenaza de ransomware. Puede recuperar una lista de estos archivos sospechosos, así como eliminarlos de un volumen.
Varias mejoras de seguridad:: Existen varias mejoras de seguridad generales que amplían los protocolos existentes e introducen nuevas funcionalidades. Se han realizado mejoras en IPSEC, la administración de claves, la configuración SSH y los permisos de archivo.
Dominios CIFS y grupos locales:: La compatibilidad con dominios CIFS se ha añadido en el nivel de clúster y SVM. Puede recuperar la configuración de dominio, así como crear y eliminar controladores de dominio preferidos.
Análisis de volúmenes ampliados:: Los análisis de volúmenes y las métricas se han ampliado mediante extremos adicionales para dar soporte a los principales archivos, directorios y usuarios.
Mejoras de soporte:: La compatibilidad se ha mejorado gracias a varias funciones nuevas. Las actualizaciones automáticas pueden mantener sus sistemas ONTAP actualizados descargando y aplicando las actualizaciones de software más recientes. También puede recuperar y gestionar los volcados de memoria generados por un nodo.




== ONTAP 9.9.1

ONTAP 9.9.1 sigue ampliando las funcionalidades de la API DE REST de ONTAP. Hay nuevos extremos API para las funciones existentes de ONTAP, incluidos los conjuntos DE puertos SAN y la seguridad del directorio de archivos vServer. Además, se han agregado extremos para admitir nuevas funciones y mejoras de ONTAP 9.9.1. Y también se ha mejorado la documentación relacionada. A continuación se presenta un resumen de las mejoras.

Asignación de ONAPI a la API DE REST de ONTAP 9:: Para ayudarle a realizar la transición del código de automatización de ONTAP a la API DE REST, NetApp proporciona documentación de asignación de API. Esta referencia incluye una lista de llamadas de ONTAPI y el equivalente de API DE REST para cada una. El documento de asignación se ha actualizado para incluir los nuevos puntos finales de la API de ONTAP 9.9.1. Consulte link:migrate/mapping.html["Asignación de la API DE REST a la API de ONTAP"] si quiere más información.
Extremos de API para nuevas funciones de núcleo de ONTAP 9.9.1:: Se ha añadido compatibilidad con las nuevas funciones de ONTAP 9.9.1 que no están disponibles a través de la API ONTAP a la API DE REST. Esto incluye compatibilidad con iGroups anidados y Google Cloud Key Management Services.
Soporte mejorado para la transición A REPOSO desde ONAPI:: Ahora, más de las llamadas de ONTAPI heredadas tienen equivalentes de API DE REST correspondientes. Esto incluye usuarios y grupos Unix locales, administración de seguridad de archivos NTFS sin necesidad de un cliente, conjuntos DE puertos SAN y atributos de espacio de volumen. Estos cambios también se incluyen en la documentación actualizada de asignación de ONTAP PARA REST.
Documentación en línea mejorada:: La página de referencia de documentación en línea de ONTAP ahora incluye etiquetas que indican la versión de ONTAP cuando se introdujo cada extremo o parámetro DE REST, incluidos los nuevos con ONTAP 9.9.1.




== ONTAP 9.8

ONTAP 9.8 incluye varias funciones nuevas que mejoran la capacidad para automatizar la implementación y la gestión de los sistemas de almacenamiento de ONTAP. Además, se ha mejorado el soporte para ayudar en la transición AL DESCANSO desde la API ONTAAPI heredada.

Asignación de ONAPI a la API DE REST de ONTAP 9:: Para ayudarle a actualizar la automatización ONTAPI, NetApp proporciona una lista de llamadas ONTAPI que requieren uno o más parámetros de entrada, junto con una asignación de dichas llamadas a la llamada a la API DE REST de ONTAP 9 equivalente. Consulte link:migrate/mapping.html["Asignación de la API DE REST a la API de ONTAP"] si quiere más información.
Puntos finales de API para las nuevas funciones de ONTAP 9.8:: Se ha añadido compatibilidad con las nuevas funciones de ONTAP 9.8 no disponibles a través de ONTAPI a la API DE REST. Esto incluye soporte de API DE REST para bloques y servicios de ONTAP S3, sincronización activa de SnapMirror (anteriormente, SnapMirror Business Continuity) y análisis de sistemas de archivos.
Soporte ampliado para una mayor seguridad:: La seguridad se ha mejorado gracias al soporte de varios servicios y protocolos, entre los que se incluyen Azure Key Vault, Google Cloud Key Management Services, IPSec y solicitudes de firma de certificados.
Mejoras para mejorar la simplicidad:: ONTAP 9.8 ofrece flujos de trabajo más eficientes y modernos utilizando la API REST. Por ejemplo, las actualizaciones de firmware con un solo clic ahora están disponibles para varios tipos diferentes de firmware.
Documentación en línea mejorada:: La página de documentación en línea de ONTAP incluye etiquetas que indican la versión de ONTAP de que se introdujo cada extremo o parámetro REST, incluidos los nuevos de 9,8.
Soporte mejorado para la transición A REPOSO desde ONAPI:: Ahora, más llamadas de ONTAAPI heredadas tienen equivalentes de API DE REST correspondientes. También hay documentación disponible para ayudar a identificar qué extremo DE REST se debe utilizar en lugar de una llamada ONAPI existente.
Métricas de rendimiento ampliadas:: Se ampliaron las métricas de rendimiento de la API DE REST para incluir varios objetos nuevos de almacenamiento y red.




== ONTAP 9.7

ONTAP 9.7 amplía el alcance funcional de la API DE REST de ONTAP introduciendo tres categorías de recursos nuevas, cada una con varios extremos DE REST:

* NDMP
* Almacén de objetos
* SnapLock


ONTAP 9.7 también introduce uno o varios extremos DE REST nuevos en varias de las categorías de recursos existentes:

* Clúster
* NAS
* Redes
* NVMe
* SAN
* Seguridad
* Reducida
* Soporte técnico




== ONTAP 9.6

ONTAP 9.6 amplía considerablemente el soporte de API DE REST que se introdujo originalmente en ONTAP 9.4. La API DE REST de ONTAP 9.6 es compatible con la mayoría de las tareas de configuración y administración de ONTAP.

Las API DE REST en ONTAP 9.6 incluyen las siguientes áreas clave y muchas más:

* Configuración del clúster
* Configuración de protocolos
* El provisionamiento
* Supervisión del rendimiento
* Protección de datos
* Gestión de datos para aplicaciones

