---
sidebar: sidebar 
permalink: rn/known_limitations.html 
keywords: limitations, known limitations 
summary: La API DE REST de ONTAP tiene ciertas limitaciones o restricciones que pueden afectar al uso de la API y al desarrollo de código de automatización. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La API DE REST de ONTAP tiene ciertas limitaciones o restricciones que pueden afectar al uso de la API y al desarrollo de código de automatización. Estas restricciones se describen a continuación. En general, cada una de ellas se aplica a todas las versiones de ONTAP compatibles donde esté disponible la API DE REST. Consulte el campo _ONTAP releases_ para obtener más información.


NOTE: La primera API DE REST se empezó a ofrecer con ONTAP 9.6.

.Solicitudes de API REST rechazadas cuando la cola de entrada está llena
_ONTAP releases: Todos los soportados_

ONTAP recibe cada solicitud de cliente API DE REST y se coloca en una cola de entrada antes de procesarse. En momentos de tasas de llegada extremadamente altas, la cola de espera de entrada que contiene estas solicitudes de API puede llenarse temporalmente. Cuando esto ocurre, se rechaza cada solicitud de desbordamiento adicional. En estas situaciones:

* ONTAP reconoce que la conexión entrante supera la profundidad de la cola de espera y registra un mensaje que indica que está fallando la conexión.
* El cliente REST observa la conexión fallida, aunque el comportamiento exacto puede depender del cliente. Por ejemplo, con un cliente NMSDK aparece el mensaje "error al conectarse a SSL".


El llenado de la cola de espera de entrada de la API REST es un evento raro. Pero rechazar el exceso de peticiones ofrece protección contra ataques dos.
