---
sidebar: sidebar 
permalink: migrate/blogs_migrate.html 
keywords: blogs, blog articles 
summary: Hay varios artículos de blog disponibles para ayudarle a comprender mejor cómo migrar de ONAPI a la API DE REST de ONTAP. 
---
= Artículos de blog
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Hay varios artículos de blog disponibles para ayudarle a comprender mejor cómo migrar de ONAPI a la API DE REST de ONTAP.

.Asignación de ONTAP a REST
NetApp proporciona soporte para pasar de la API ONTAAPI exclusiva a la API DE REST de ONTAP a la documentación de asignación.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["netapp.io/2020/12/17/ontapi-to-rest-mapping"^]

.Transforme su automatización en la API DE REST de ONTAP desde ONTAAPI
Existen varias tecnologías disponibles para ayudarle a transformar su entorno de automatización de ONTAP según la API DE REST.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/["www.netapp.com/blog/transform-automation-ontap-rest-api"^]

.Utilizando el traspaso de interfaz de línea de comandos privada con la API REST de ONTAP
Para ayudar a los usuarios de la interfaz de línea de comandos y de ONTAP a realizar la transición a la API DE REST de ONTAP, ONTAP proporciona un extremo de API de REST privado que se puede usar para acceder a cualquier comando de la CLI.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api"^]

.Traslado desde ONTAPI mediante la herramienta de informes de uso de ONTAPI
NetApp proporciona una herramienta para ayudar a los clientes y partners a realizar la transición a la API DE REST de ONTAP.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["netapp.io/2022/03/21/herramienta-elaboración de informes-uso-ontapi-from-ontapi-ontapi-ontapi"^]
