---
sidebar: sidebar 
permalink: migrate/overview.html 
keywords: ONTAPI, migrate, migrate to REST API 
summary: Si utiliza la API ONTAPI, se le recomienda que comience a migrar a la API DE REST de ONTAP. 
---
= Inhabilitación de ONTAPI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La API de ONTAPI (ZAPI) es el conjunto original de llamadas exclusivas que se incluyen con el software ONTAP de NetApp para admitir la automatización de las tareas de administración y gestión del almacenamiento de datos. La interfaz ONTAPI se deshabilitará en futuras versiones de ONTAP. Si utiliza ONTAPI, debe planificar la migración a la API DE REST DE ONTAP.

NetApp introdujo por primera vez la API DE REST con ONTAP 9.6. Desde entonces, la API REST ha continuado expandiéndose y madurando. Ahora ofrece la opción preferida y estratégica al automatizar la administración de sus implementaciones de ONTAP. Existen muchas herramientas y recursos útiles para ayudarle a realizar la migración.

.Información relacionada
* https://mysupport.netapp.com/info/communications/ECMLP2880232.html["CPC-00410 Fin de la disponibilidad: ONTAPI"^]
* https://devnet.netapp.com/restapi.php["DevNet de NetApp: API de REST DE ONTAP"^]

