---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Existen varios recursos adicionales a los que puede acceder para obtener ayuda y encontrar más información sobre cómo automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP. 
---
= Leer más
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varios recursos adicionales disponibles para ayudarle a automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP.



== Artículos de blog

* Un buen resumen de las tecnologías actuales de automatización de ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Nueva normalidad para la automatización"^]

* Una introducción al acceso y el uso de los scripts de ejemplos de Python en GitHub para la API DE REST DE ONTAP.
+
https://netapp.io/2020/04/23/ontap-rest-apis["Comience con scripts de ejemplo en GitHub"^]

* La conmutación desde la CLI proporciona una técnica para ejecutar comandos de la CLI de ONTAP mediante la API DE REST.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["Utilizando el traspaso de interfaz de línea de comandos privada con la API REST de ONTAP"^]

* Si es nuevo en usar Ansible para la automatización de ONTAP, este es un buen lugar desde el que empezar.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["Introducción a NetApp y Ansible: Instale Ansible"^]

* Puede analizar el uso de la API de REST DE ONTAP para gestionar la seguridad y los permisos de los archivos.
+
https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis["Gestión simplificada de permisos de seguridad de archivos con API DE REST de ONTAP"^]

* Puede supervisar los eventos de ONTAP para conocer la actividad del sistema. La configuración y la gestión de estos eventos pueden automatizarse mediante la API de REST.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["API DE REST de ONTAP: Automatice la notificación de eventos de alta gravedad"^]

* Es posible usar la API de REST para configurar roles y niveles de acceso como parte de un entorno de seguridad de RBAC.
+
https://netapp.io/2022/06/26/rbac-using-ontap-rest-apis["Control de acceso basado en roles (RBAC) mediante las API DE REST DE ONTAP"^]

* NetApp proporciona scripts de muestra de Python para usar la API de REST DE ONTAP.
+
https://netapp.io/2020/04/23/ontap-rest-apis["¡Los scripts de ejemplo de Python de la API REST DE ONTAP ya están disponibles en GitHub!"^]

* Descansos de café con DESCANSO (6 episodios).
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Conceptos básicos de las API DE REST de ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Funciones de las API DE REST DE ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Formación práctica de ONTAP REST mediante Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["Herramienta de informes ONTAPI (ZAPI)"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Transferencia de CLI privada"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 funciones mágicas que simplifican la automatización del almacenamiento de ONTAP"^]






== Vídeos

* Una buena introducción a la biblioteca cliente de NetApp Python y cómo comenzar a escribir código usando la biblioteca.
+
video::Wws3SB5d9Ss[youtube,width=848,height=480]
* Echa un vistazo a los módulos certificados de Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Una colección de videos en NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatice la gestión de NetApp ONTAP"^]





== Formación técnica y eventos

* Presentación de Insight 2022 (26 minutos).
+
https://media.netapp.com/video-detail/152137a0-4153-59dc-ad7d-232af1785dd5/modernize-your-ontap-storage-management-with-ontap-rest-apis-1837["Moderniza la gestión del almacenamiento de ONTAP con la API de REST DE ONTAP"^]



* Presentación de Insight 2021 (31 minutos).
+
https://media.netapp.com/video-detail/f353c28a-2364-5e5e-bf86-5d7ef66360fe/netapp-ontap-save-time-and-simplify-using-rest-apis-brk-1103-3["NetApp ONTAP: Ahorre tiempo y simplifique con las API de REST"^]



* Servicios de aprendizaje de NetApp.
+
https://netapp.sabacloud.com/Saba/Web_spf/NA1PRD0047/app/shared;spf-url=common%2Fledetail%2FSTRSW-ILT-RSTAPI["Automatiza la administración del almacenamiento con la API de REST DE ONTAP y Ansible"^]





== Base de conocimientos de NetApp

* Si se encuentra con un problema con la API DE REST DE ONTAP, puede notificarlo en NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["Cómo informar de problemas en la API de REST DE ONTAP y la biblioteca del cliente Python de la API DE REST DE ONTAP"^]

* Si identifica una brecha funcional en la API DE REST DE ONTAP, puede solicitar una nueva función para la API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Cómo solicitar una función a la API de REST DE ONTAP"^]


