---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Existen varios recursos adicionales a los que puede acceder para obtener ayuda y encontrar más información sobre cómo automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP. 
---
= Obtenga más información sobre la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varios recursos adicionales disponibles para ayudarle a automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP.



== Artículos de blog

Los artículos del blog se organizan en varias secciones basadas en el tema.



=== Generales

* Un buen resumen de las tecnologías actuales de automatización de ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Nueva normalidad para la automatización"^]

* Puede supervisar los eventos de ONTAP para conocer la actividad del sistema. La configuración y la gestión de estos eventos pueden automatizarse mediante la API de REST.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["API DE REST de ONTAP: Automatice la notificación de eventos de alta gravedad"^]

* Descansos de café con DESCANSO (6 episodios):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Conceptos básicos de las API DE REST de ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Funciones de las API DE REST DE ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Formación práctica de ONTAP REST mediante Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["Herramienta de informes ONTAPI (ZAPI)"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Transferencia de CLI privada"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 funciones mágicas que simplifican la automatización del almacenamiento de ONTAP"^]






=== Biblioteca de clientes de Python

* Este blog ofrece una buena introducción a las características de la biblioteca cliente de Python de ONTAP.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Simplifique el consumo de API DE REST DE ONTAP con la biblioteca cliente de Python"^]





=== Migrar a la API de REST

* Existen varias tecnologías disponibles para ayudarle a transformar su entorno de automatización de ONTAP según la API DE REST.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["Transforme su automatización en la API DE REST de ONTAP desde ONTAAPI"^]





== Vídeos

* Una buena introducción a la biblioteca cliente de NetApp Python y cómo comenzar a escribir código usando la biblioteca.
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Echa un vistazo a los módulos certificados de Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Una colección de videos en NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatice la gestión de NetApp ONTAP"^]





== Base de conocimientos de NetApp

* Si se encuentra con un problema con la API DE REST DE ONTAP, puede notificarlo en NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["Cómo informar de problemas en la API de REST DE ONTAP y la biblioteca del cliente Python de la API DE REST DE ONTAP"^]

* Si identifica una brecha funcional en la API DE REST DE ONTAP, puede solicitar una nueva función para la API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Cómo solicitar una función a la API de REST DE ONTAP"^]


