---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Existen varios recursos adicionales a los que puede acceder para obtener ayuda y encontrar más información sobre cómo automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP. 
---
= Obtenga más información sobre la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varios recursos adicionales disponibles para ayudarle a automatizar la implementación y la administración de sus sistemas de almacenamiento de ONTAP.



== Artículos de blog

Los artículos del blog se organizan en varias secciones basadas en el tema.



=== Generales

* Un buen resumen de las tecnologías actuales de automatización de ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Nueva normalidad para la automatización"^]

* Si es nuevo en usar Ansible para la automatización de ONTAP, este es un buen lugar desde el que empezar.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["Introducción a NetApp y Ansible: Instale Ansible"^]

* Puede analizar el uso de la API de REST DE ONTAP para gestionar la seguridad y los permisos de los archivos.
+
https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis["Gestión simplificada de permisos de seguridad de archivos con API DE REST de ONTAP"^]

* Puede supervisar los eventos de ONTAP para conocer la actividad del sistema. La configuración y la gestión de estos eventos pueden automatizarse mediante la API de REST.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["API DE REST de ONTAP: Automatice la notificación de eventos de alta gravedad"^]

* Es posible usar la API de REST para configurar roles y niveles de acceso como parte de un entorno de seguridad de RBAC.
+
https://netapp.io/2022/06/26/rbac-using-ontap-rest-apis["Control de acceso basado en roles (RBAC) mediante las API DE REST DE ONTAP"^]

* Descansos de café con DESCANSO (6 episodios):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Conceptos básicos de las API DE REST de ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Funciones de las API DE REST DE ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Formación práctica de ONTAP REST mediante Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["Herramienta de informes ONTAPI (ZAPI)"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Transferencia de CLI privada"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 funciones mágicas que simplifican la automatización del almacenamiento de ONTAP"^]






=== Biblioteca de clientes de Python

* Una introducción al uso de los scripts de ejemplo de Python que NetApp proporciona en GitHub para acceder a la API de REST DE ONTAP.
+
https://netapp.io/2020/04/23/ontap-rest-apis["¡Los scripts de ejemplo de Python de la API REST DE ONTAP ya están disponibles en GitHub!"^]

* Este blog ofrece una buena introducción a las características de la biblioteca cliente de Python de ONTAP.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Simplifique el consumo de API DE REST DE ONTAP con la biblioteca cliente de Python"^]

* Esta es una serie de tres partes de blogs sobre cómo empezar con la biblioteca cliente de Python:
+
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt1["Parte 1"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt2["Parte 2"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt3["Parte 3"^]






=== Migrar a la API de REST

* NetApp proporciona soporte para pasar de la API ONTAAPI exclusiva a la API DE REST de ONTAP a la documentación de asignación.
+
https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["Asignación de ONTAP a REST"^]

* Existen varias tecnologías disponibles para ayudarle a transformar su entorno de automatización de ONTAP según la API DE REST.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["Transforme su automatización en la API DE REST de ONTAP desde ONTAAPI"^]

* Para ayudar a los usuarios de la interfaz de línea de comandos y de ONTAP a realizar la transición a la API DE REST de ONTAP, ONTAP proporciona un extremo de API de REST privado que se puede usar para acceder a cualquier comando de la CLI.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Utilizando el traspaso de interfaz de línea de comandos privada con la API REST de ONTAP"^]

* NetApp proporciona una herramienta para ayudar a los clientes y partners a realizar la transición a la API DE REST de ONTAP.
+
https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["Realizar la transición desde ONTAPI(ZAPI) con la herramienta de generación de informes de uso de ONTAPI"^]





== Vídeos

* Una buena introducción a la biblioteca cliente de NetApp Python y cómo comenzar a escribir código usando la biblioteca.
+
video::Wws3SB5d9Ss[youtube,width=848,height=480]
* Echa un vistazo a los módulos certificados de Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Una colección de videos en NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatice la gestión de NetApp ONTAP"^]





== Formación técnica y eventos

* Presentación de Insight 2022 (26 minutos).
+
https://media.netapp.com/video-detail/152137a0-4153-59dc-ad7d-232af1785dd5/modernize-your-ontap-storage-management-with-ontap-rest-apis-1837["Moderniza la gestión del almacenamiento de ONTAP con la API de REST DE ONTAP"^]



* Presentación de Insight 2021 (31 minutos).
+
https://media.netapp.com/video-detail/f353c28a-2364-5e5e-bf86-5d7ef66360fe/netapp-ontap-save-time-and-simplify-using-rest-apis-brk-1103-3["NetApp ONTAP: Ahorre tiempo y simplifique con las API de REST"^]



* Servicios de aprendizaje de NetApp.
+
https://netapp.sabacloud.com/Saba/Web_spf/NA1PRD0047/app/shared;spf-url=common%2Fledetail%2FSTRSW-ILT-RSTAPI["Automatiza la administración del almacenamiento con la API de REST DE ONTAP y Ansible"^]





== Base de conocimientos de NetApp

* Si se encuentra con un problema con la API DE REST DE ONTAP, puede notificarlo en NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["Cómo informar de problemas en la API de REST DE ONTAP y la biblioteca del cliente Python de la API DE REST DE ONTAP"^]

* Si identifica una brecha funcional en la API DE REST DE ONTAP, puede solicitar una nueva función para la API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Cómo solicitar una función a la API de REST DE ONTAP"^]


