---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation 
summary: La referencia de la API contiene los detalles sobre todas las llamadas API DE REST de ONTAP, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST. 
---
= Referencia de API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La referencia de la API contiene los detalles sobre todas las llamadas API DE REST de ONTAP, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST.


NOTE: Puede acceder al contenido de referencia de API en línea en el sistema ONTAP local o a una copia estática de la documentación que mantiene NetApp.



== Acceda a la página de documentación de la API de ONTAP

[role="lead"]
Puede acceder a la página de documentación en línea de la API de ONTAP en el sistema ONTAP local.

.Antes de empezar
Debe tener lo siguiente:

* La dirección IP o el nombre de host de la LIF de gestión de clústeres de ONTAP
* Nombre de usuario y contraseña para una cuenta con autoridad para acceder a la API DE REST de ONTAP


.Pasos
. Escriba la dirección URL en su navegador y pulse *Intro*:
+
`https://<ip_address>/docs/api`

. Inicie sesión mediante la cuenta de ONTAP.
+
La página de documentación de la API de ONTAP se muestra con las llamadas API organizadas en categorías de recursos principales en la parte inferior.

. Como ejemplo de una llamada individual a la API, desplácese hacia abajo hasta la categoría *cluster* y haga clic en *GET /cluster*.




== Acceda a una copia de la documentación de referencia de la API de REST de ONTAP

[role="lead"]
Puede acceder a una copia de la documentación de referencia de la API de REST de ONTAP mediante los enlaces proporcionados a continuación. La documentación de referencia de la API se mantiene con la versión de ONTAP.

* https://library.netapp.com/ecmdocs/ECMLP2885799/html/["ONTAP 9.13.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2884821/html/["ONTAP 9.12.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2882307/html/["ONTAP 9.11.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2879871/html/["ONTAP 9.10.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2876964/html/["ONTAP 9.9.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2874708/html/["ONTAP 9.8"^]
* https://library.netapp.com/ecmdocs/ECMLP2862544/html/["ONTAP 9.7"^]
* https://library.netapp.com/ecmdocs/ECMLP2856304/html/["ONTAP 9.6"^]


.Información relacionada
https://devnet.netapp.com/restapi.php["DevNet de NetApp: API DE REST de ONTAP"^]
