---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation, online reference, swagger 
summary: La referencia de API contiene detalles sobre las llamadas API DE REST DE ONTAP, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST. 
---
= Referencia de la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La referencia de API contiene detalles sobre las llamadas API DE REST DE ONTAP, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST.


NOTE: Es posible acceder a la documentación de referencia de la API de REST en uno de varios sitios de acuerdo con la versión de ONTAP. También hay disponible una copia de la documentación equivalente a través de la interfaz de usuario de Swagger en el sistema ONTAP local.



== Acceda en línea a la documentación de referencia de API de ONTAP

Puede acceder a la documentación actual https://docs.netapp.com/us-en/ontap-restapi/ontap/getting_started_with_the_ontap_rest_api.html["Referencia de API de REST de ONTAP"^] en línea. También hay un selector de versiones disponible para acceder a versiones anteriores de la documentación basada en la versión de ONTAP.



== Acceda a la documentación de referencia de la API de ONTAP a través de la interfaz de usuario de Swagger

Puede acceder a la documentación de la API de REST DE ONTAP a través de la interfaz de usuario de Swagger en el sistema ONTAP local.

.Antes de empezar
Debe tener lo siguiente:

* La dirección IP o el nombre de host de la LIF de gestión de clústeres de ONTAP
* Nombre de usuario y contraseña para una cuenta con autoridad para acceder a la API DE REST de ONTAP


.Pasos
. Escriba la dirección URL en su navegador y pulse *Intro*:
+
`https://<ip_address>/docs/api`

. Inicie sesión mediante la cuenta de ONTAP.
+
La página de documentación de la API de ONTAP se muestra con las llamadas API organizadas en categorías de recursos principales en la parte inferior.

. Como ejemplo de una llamada individual a la API, desplácese hacia abajo hasta la categoría *cluster* y haga clic en *GET /cluster*.

