---
sidebar: sidebar 
permalink: workflows/prepare_workflows.html 
keywords: workflows, preparation, prepare to use workflows 
summary: Debe prepararse antes de utilizar los procesos de flujo de trabajo. 
---
= Prepárese para usar los flujos de trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe prepararse antes de utilizar los procesos de flujo de trabajo.



=== Llamadas API que se usan en los flujos de trabajo

La página de documentación en línea de la API de ONTAP incluye los detalles de cada llamada a la API DE REST. En lugar de repetir estos detalles aquí, cada llamada de API utilizada en los ejemplos de flujo de trabajo incluye solo la información necesaria para localizar la llamada en la página de documentación. Después de localizar una llamada API específica, puede revisar los detalles completos de la llamada, incluidos los parámetros de entrada, formatos de salida, códigos de estado HTTP y tipo de procesamiento de solicitudes.

Se incluye la siguiente información para cada llamada de API dentro de un flujo de trabajo para ayudar a localizar la llamada en la página de documentación:

* Categoría
+
Las llamadas API se organizan en la página de documentación en categorías o áreas relacionadas con la función. Para ubicar una llamada API específica, desplácese hasta la parte inferior de la página y haga clic en la categoría API correspondiente.

* Método HTTP
+
El método HTTP identifica la acción realizada en un recurso. Cada llamada API se ejecuta mediante un único método HTTP.

* Ruta
+
La ruta determina el recurso específico al que se aplica la acción como parte de la realización de una llamada. La cadena de ruta de acceso se anexa a la URL de núcleo para formar la URL completa que identifica el recurso.





=== Construcción de una URL para acceder directamente a la API DE REST

Además de la página de documentación de ONTAP, también puede acceder a la API DE REST de ONTAP directamente a través de un lenguaje de programación como Python. En este caso, la URL principal es ligeramente diferente a la URL utilizada al acceder a la página de documentación en línea. Al acceder a la API directamente, debe realizar la adición `/api` al dominio y la cadena de puerto. Por ejemplo: `https://ontap.mycompany.com/api`

.Enlaces relacionados
* link:../rest/access_rest_api.html["Cómo acceder a la API de ONTAP"]
* link:../resources/overview_categories.html["Resumen de recursos DE REST"]

