---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact, job, job state 
summary: Puede actualizar la información de contacto de un clúster de. Debido a que la solicitud se procesa de forma asíncrona, este flujo de trabajo también ilustra cómo determinar si el trabajo en segundo plano asociado se ha completado correctamente. 
---
= Actualice el contacto del clúster y confirme el estado del trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede actualizar la información de contacto de un clúster de. Debido a que la solicitud se procesa de forma asíncrona, este flujo de trabajo también ilustra cómo determinar si el trabajo en segundo plano asociado se ha completado correctamente.



== Paso 1: Actualice la información de contacto del clúster

Puede emitir una llamada API para actualizar la información de contacto del clúster.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PARCHE | /cluster 
|===
.Tipo de procesamiento
Asíncrona

.Ejemplo de curl
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Ejemplo de resultado JSON
Se devuelve el objeto de trabajo. Debe guardar el identificador de trabajo para utilizarlo en el siguiente paso como variable $JOB_ID.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Paso 2: Recuperar el estado del trabajo

Debe recuperar el estado del trabajo para determinar si la solicitud asíncrona se ha completado correctamente.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /cluster/trabajos/{uuid} 
|===
.Tipo de procesamiento
Síncrona

.Ejemplo de curl
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Ejemplo de resultado JSON
El valor de estado y otros campos se incluyen en el objeto de trabajo devuelto.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----


== Paso 3: Confirme la información de contacto del clúster

Realice el flujo de trabajo link:../workflows/wf_get_cluster.html["Obtener la configuración del clúster"]. Debe configurar la `fields` parámetro de consulta a. `contact`.
