---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact 
summary: Puede actualizar la información de contacto de un clúster de. Debido a que la solicitud se procesa de forma asíncrona, también debe determinar si el trabajo en segundo plano asociado se completó correctamente. 
---
= Actualice el contacto del clúster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede actualizar la información de contacto de un clúster de. Debido a que la solicitud se procesa de forma asíncrona, también debe determinar si el trabajo en segundo plano asociado se completó correctamente.



== Paso 1: Actualice la información de contacto del clúster

Puede emitir una llamada API para actualizar la información de contacto del clúster.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PARCHE | /api/clúster 
|===
.Tipo de procesamiento
Asíncrona

.Ejemplo de curl
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Ejemplo de resultado JSON
Se devuelve un objeto de trabajo. Debe guardar el identificador de trabajo para utilizarlo en el siguiente paso.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Paso 2: Recuperar el estado del trabajo

Realice el flujo de trabajo link:../workflows/wf_jobs_get_job.html["Obtener instancia de trabajo"] y confirme el `state` el valor es `success`.



== Paso 3: Confirme la información de contacto del clúster

Realice el flujo de trabajo link:../workflows/wf_cls_get_cluster.html["Obtener la configuración del clúster"]. Debe configurar la `fields` parámetro de consulta a. `contact`.
