---
sidebar: sidebar 
permalink: workflows/wf_ems_create_notification.html 
keywords: support, ems, event management system, create ems, create ems notification 
summary: Puede utilizar el siguiente flujo de trabajo para crear un nuevo destino de notificación de EMS para recibir los mensajes de eventos seleccionados. 
---
= Cree una notificación de EMS mediante la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar el siguiente flujo de trabajo para crear un nuevo destino de notificación de EMS para recibir los mensajes de eventos seleccionados.



== Paso 1: Configure la configuración del correo electrónico en todo el sistema

Puede emitir la siguiente llamada API para configurar los ajustes del correo electrónico para todo el sistema.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PARCHE | /api/support/ems 
|===
.Tipo de procesamiento
Síncrona

.Parámetros de entrada adicionales para los ejemplos de Curl
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| mail_de | Consulta | Sí | Establece el `from` en los mensajes de correo electrónico de notificación. 


| servidor_correo | Consulta | Sí | Configura el servidor de correo SMTP de destino. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----


== Paso 2: Defina un filtro de mensajes

Puede emitir una llamada API para definir una regla de filtro que coincida con los mensajes.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /api/support/ems/filters 
|===
.Tipo de procesamiento
Síncrona

.Parámetros de entrada adicionales para los ejemplos de Curl
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| Filtro | Cuerpo | Sí | Incluye los valores para la configuración del filtro. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/filters" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "name": "test-filter",
  "rules.type": ["include"],
  "rules.message_criteria.severities": ["emergency"]
}
----


== Paso 3: Crear un destino de mensaje

Puede emitir una llamada API para crear un destino de mensaje.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /api/support/ems/destinations 
|===
.Tipo de procesamiento
Síncrona

.Parámetros de entrada adicionales para los ejemplos de Curl
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| Configuración de destino | Cuerpo | Sí | Incluye los valores del destino del evento. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/destinations" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Ejemplo de entrada JSON
[source, curl]
----
{
  "name": "test-destination",
  "type": "email",
  "destination": "administrator@mycompany.com",
  "filters.name": ["important-events"]
}
----