---
sidebar: sidebar 
permalink: workflows/wf_jobs_get_job.html 
keywords: workflow, job, job state 
summary: Puede recuperar la instancia de un trabajo de ONTAP específico. Normalmente, lo haría para determinar si el trabajo y la operación asociada se han completado correctamente. 
---
= Obtener instancia de trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede recuperar la instancia de un trabajo de ONTAP específico. Normalmente, lo haría para determinar si el trabajo y la operación asociada se han completado correctamente.


NOTE: Necesita el UUID del objeto de trabajo, que normalmente se proporciona después de emitir una solicitud asíncrona. También revise link:../rest/asynchronous_processing.html["Procesamiento asíncrono mediante el objeto Job"] Antes de trabajar con trabajos internos de ONTAP.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /api/cluster/jobs/{uuid} 
|===
.Tipo de procesamiento
Síncrona

.Parámetros de entrada adicionales para los ejemplos de Curl
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| $JOB_ID | Ruta | Sí | Necesario para identificar el trabajo que se solicita. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Ejemplo de resultado JSON
El valor de estado y otros campos se incluyen en el objeto de trabajo devuelto. El trabajo de este ejemplo se ejecutó como parte de la actualización de un clúster de ONTAP.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----