---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_apply_permissions.html 
keywords: nas, file security, sacl, dacl, permissions, apply permissions 
summary: Puede aplicar un nuevo descriptor de seguridad a un archivo o carpeta específicos. 
---
= Aplique nuevos permisos a un archivo mediante la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede aplicar un nuevo descriptor de seguridad a un archivo o carpeta específicos.



== Paso 1: Aplique los nuevos permisos

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /api/protocols/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo de procesamiento
Asíncrona

.Parámetros de entrada adicionales para ejemplos de cURL
Además de los parámetros comunes con todas las llamadas a la API REST, los siguientes parámetros también se utilizan en el ejemplo curl de este paso.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| $SVM_ID | Ruta | Sí | Este es el UUID de la SVM que contiene el archivo. 


| RUTA_FILE | Ruta | Sí | Esta es la ruta al archivo o carpeta. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Paso 2: Recuperar el estado del trabajo

Realice el flujo de trabajo link:../workflows/wf_jobs_get_job.html["Obtener instancia de trabajo"] y confirme el `state` el valor es `success`.
