---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_delete_ace.html 
keywords: nas, file security, access control entry, ace, delete ace 
summary: 'Puede eliminar una entrada de control de acceso (ACE) existente de un archivo o carpeta específicos. El cambio se propaga a cualquier objeto secundario.' 
---
= Eliminar una entrada de control de acceso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede eliminar una entrada de control de acceso (ACE) existente de un archivo o carpeta específicos. El cambio se propaga a cualquier objeto secundario.



== Paso 1: Eliminar el ACE

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| ELIMINAR | /api/protocols/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo de procesamiento
Asíncrona

.Parámetros de entrada adicionales para ejemplos de cURL
Además de los parámetros comunes con todas las llamadas a la API REST, los siguientes parámetros también se utilizan en el ejemplo curl de este paso.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| $SVM_ID | Ruta | Sí | Este es el UUID de la SVM que contiene el archivo. 


| RUTA_FILE | Ruta | Sí | Esta es la ruta al archivo o carpeta. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request DELETE --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Paso 2: Recuperar el estado del trabajo

Realice el flujo de trabajo link:../workflows/wf_jobs_get_job.html["Obtener instancia de trabajo"] y confirme el `state` el valor es `success`.
