---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_update_sd.html 
keywords: nas, file security, security descriptor, sd, update security descriptor 
summary: Puede actualizar un descriptor de seguridad específico a un archivo o carpeta específicos, incluidos los indicadores de propietario, grupo o control principal. 
---
= Actualice la información del descriptor de seguridad mediante la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede actualizar un descriptor de seguridad específico a un archivo o carpeta específicos, incluidos los indicadores de propietario, grupo o control principal.



== Paso 1: Actualice el descriptor de seguridad

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PARCHE | /api/protocols/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo de procesamiento
Asíncrona

.Parámetros de entrada adicionales para ejemplos de cURL
Además de los parámetros comunes con todas las llamadas a la API REST, los siguientes parámetros también se utilizan en el ejemplo curl de este paso.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| $SVM_ID | Ruta | Sí | Este es el UUID de la SVM que contiene el archivo. 


| RUTA_FILE | Ruta | Sí | Esta es la ruta al archivo o carpeta. 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Paso 2: Recuperar el estado del trabajo

Realice el flujo de trabajo link:../workflows/wf_jobs_get_job.html["Obtener instancia de trabajo"] y confirme el `state` el valor es `success`.
