---
sidebar: sidebar 
permalink: python/learn-about-pcl.html 
keywords: learn about python client library, learn about pcl, pcl overview, pcl 
summary: La biblioteca del cliente de Python de NetApp ONTAP es un paquete que puede instalar y utilizar para escribir rápidamente scripts que accedan a la API DE REST DE ONTAP. Deberá preparar el entorno de tiempo de ejecución local antes de utilizarlo. 
---
= Obtenga información sobre la biblioteca cliente de Python de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La biblioteca del cliente de Python de NetApp ONTAP es un paquete que puede instalar y utilizar para escribir rápidamente scripts que accedan a la API DE REST DE ONTAP. Deberá preparar el entorno de tiempo de ejecución local antes de utilizarlo.


NOTE: También debe revisar los recursos disponibles en link:../additional/learn_more.html["Obtenga más información sobre la API de REST DE ONTAP"].

.Beneficios y funciones
Puede utilizar la biblioteca cliente de Python para desarrollar rápidamente código robusto para automatizar la administración de sus implementaciones de ONTAP. Proporciona varios servicios subyacentes, como:

* Gestión de conexiones
* Procesamiento asíncrono
* Manejo de excepciones
* Mensajes de error uniformes


.Nombre y versión del paquete
El nombre del paquete de biblioteca de clientes Python es *netapp-ontap*. La versión asociada al paquete es una combinación de los números de versión principal y secundario de ONTAP a partir de los cuales se ha generado la biblioteca, junto con una versión secundaria para la biblioteca cliente dentro de la versión de ONTAP. Por ejemplo, los números de versión válidos incluyen 9,6.1, 9,6.2 y 9,7.1.

.Instalación
Debe usar la utilidad *pip* para instalar el paquete NetApp_ONTAP desde el sitio del índice de paquetes de Python (Pypi).

.Paquetes y documentación a través de la versión de ONTAP
Cada versión de ONTAP que empieza por 9,6 tiene un paquete de PyPI y documentación asociada. Consulte link:../python/packages.html["Paquetes y documentación"] para obtener más información. Los requisitos de instalación se incluyen con cada paquete y especifican diferentes versiones de las siguientes:

* python
* solicitudes
* solicitudes-correa de herramientas
* malvavisco


.Muestras de código
NetApp mantiene un repositorio de GitHub con muestras de código y otra información útil. Puede desplazarse a la carpeta _Examples_ para acceder a las muestras utilizando la biblioteca de clientes de Python. Consulte las siguientes ubicaciones en GitHub para obtener más información:

* https://github.com/NetApp/ontap-rest-python["Repositorio de GitHub DE REST de ONTAP"^]
* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Ejemplos de bibliotecas cliente Python REST DE ONTAP"^]

