---
sidebar: sidebar 
permalink: python/prepare_pcl.html 
keywords: python client library, prepare, pcl 
summary: Debe preparar el entorno de tiempo de ejecución local antes de utilizar la biblioteca de clientes de Python. 
---
= Prepárese para utilizar la biblioteca de clientes de Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe preparar el entorno de tiempo de ejecución local antes de utilizar la biblioteca de clientes de Python.

.Nombre y versión del paquete
El nombre del paquete de biblioteca de clientes Python es *netapp-ontap*. La versión asociada al paquete es una combinación de los números de versión principal y secundario de ONTAP a partir de los que se generó la biblioteca, junto con una versión secundaria para el cliente en la versión ONTAP. Por ejemplo, los números de versión válidos son: 9.6.1, 9.6.2 y 9.7.1.

.Instalación
Debe utilizar pip para instalar el paquete netapp_ontap desde el sitio web de índice de paquetes Python (PyPI).

.Paquetes y documentación a través de la versión de ONTAP
Cada versión de ONTAP que empieza por 9,6 tiene un paquete de PyPI y documentación asociada. Consulte link:../python/packages.html["Paquetes y documentación"] si quiere más información. Los requisitos de instalación se incluyen con cada paquete e incluyen diferentes versiones de las siguientes:

* python
* solicitudes
* solicitudes-correa de herramientas
* malvavisco

