---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: Es posible acceder a la API de REST de ONTAP de diferentes maneras. 
---
= Cómo acceder a la API de REST de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible acceder a la API de REST de ONTAP de diferentes maneras.



== Consideraciones sobre la red

Puedes conectarte a la API REST de ONTAP utilizando uno de varios tipos de interfaces. El LIF que elija debe estar configurado para admitir el protocolo de gestión HTTPS. Además, la configuración del firewall de su red debe permitir el tráfico HTTPS. Se admiten las siguientes interfaces:

* LIF de gestión de clústeres
* LIF de gestión de nodos
* LIF de gestión de SVM


Si bien puede utilizar cualquiera de estos LIF, la práctica recomendada es utilizar el LIF de administración de clústeres. Esto permite que el clúster se trate como una única unidad lógica y proporciona el máximo nivel de resiliencia y equilibrio de carga. Un LIF de clúster puede reubicarse dentro del clúster según sea necesario para gestionar actualizaciones planificadas, eventos de quórum y otros problemas de conectividad. Si tiene configuradas varias LIF de administración de clústeres, todas son equivalentes en lo que respecta al acceso a la API REST. Las LIF de gestión de SVM también están balanceadas de carga, pero las solicitudes enviadas a LIF con alcance a nivel de nodo se manejan localmente.



== Página de documentación en línea sobre la API de ONTAP

La página de documentación en línea de la API de ONTAP proporciona un punto de acceso cuando se utiliza un explorador web. Además de proporcionar una forma de ejecutar directamente llamadas API individuales, la página incluye una descripción detallada de la API, incluidos los parámetros de entrada y otras opciones para cada llamada. Las llamadas API se organizan en categorías funcionales. Consulte link:../resources/overview_categories.html["Resumen de recursos DE REST"] si quiere más información.

El formato de la URL que se usa para acceder a la página de documentación de la versión más reciente de la API es:

`\https://<cluster_mgmt_ip_address>/docs/api`



== Herramientas y software personalizados

Puede acceder a la API de ONTAP utilizando cualquiera de los diferentes lenguajes y herramientas de programación. Entre las opciones más populares se incluyen Python, Java, Curl y PowerShell. Programa, script o herramienta que usa la API actúa como cliente DE servicios web REST. El uso de un lenguaje de programación permite comprender mejor la API y ofrece la oportunidad de automatizar la administración de ONTAP.

El formato de la URL básica que se usa para acceder directamente a la versión más reciente de la API es:

`\https://<cluster_mgmt_ip_address>/api`

Para acceder a una versión específica de la API en la que se admiten varias versiones, el formato de la URL es:

`\https://<cluster_mgmt_ip_address>/api/v1`
