---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: accessing the rest api, lif 
summary: Es posible acceder a la API de REST de ONTAP de diferentes maneras. 
---
= Cómo acceder a la API de REST de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible acceder a la API de REST de ONTAP de diferentes maneras.



== Consideraciones sobre la red

Es posible conectarse a la API DE REST a través de las siguientes interfaces:

* LIF de gestión de clústeres
* LIF de gestión de nodos
* LIF de gestión de SVM


La LIF que elija utilizar debe estar configurada para admitir el protocolo de gestión HTTPS. Además, la configuración del firewall en la red debe permitir el tráfico HTTPS.


TIP: Siempre debe utilizar una LIF de gestión de clúster. Esto equilibrará la carga de las solicitudes de API en todos los nodos y evitará que los nodos estén desconectados o tengan problemas de conectividad. Si tiene configuradas varias LIF de gestión de clústeres, todas son equivalentes en cuanto al acceso a la API DE REST.



== Página de documentación en línea sobre la API de ONTAP

La página de documentación en línea de la API de ONTAP proporciona un punto de acceso cuando se utiliza un explorador web. Además de proporcionar una forma de ejecutar directamente llamadas API individuales, la página incluye una descripción detallada de la API, incluidos los parámetros de entrada y otras opciones para cada llamada. Las llamadas API se organizan en categorías funcionales. Consulte link:../resources/overview_categories.html["Resumen de recursos DE REST"] si quiere más información.

El formato de la URL que se usa para acceder a la página de documentación de la versión más reciente de la API es:

`\https://<cluster_mgmt_ip_address>/docs/api`



== Herramientas y software personalizados

Puede acceder a la API de ONTAP utilizando cualquiera de los diferentes lenguajes y herramientas de programación. Entre las opciones más populares se incluyen Python, Java, Curl y PowerShell. Programa, script o herramienta que usa la API actúa como cliente DE servicios web REST. El uso de un lenguaje de programación permite comprender mejor la API y ofrece la oportunidad de automatizar la administración de ONTAP.

El formato de la URL básica que se usa para acceder directamente a la versión más reciente de la API es:

`\https://<cluster_mgmt_ip_address>/api`

Para acceder a una versión específica de la API en la que se admiten varias versiones, el formato de la URL es:

`\https://<cluster_mgmt_ip_address>/api/v1`
