---
sidebar: sidebar 
permalink: get-started/first_call.html 
keywords: first REST API call, test REST API 
summary: Es posible emitir un comando curl para empezar a usar la API de REST DE ONTAP y confirmar su disponibilidad. 
---
= Tu primera llamada a la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible emitir un comando curl sencillo para comenzar a usar la API de REST DE ONTAP y confirmar su disponibilidad.

.Antes de empezar
Además de tener la utilidad cURL disponible en su estación de trabajo, necesita lo siguiente:

* La dirección IP o el FQDN de la LIF de administración del clúster de ONTAP
* Credenciales de ONTAP para una cuenta con autoridad para acceder a la API de REST DE ONTAP



NOTE: Si sus credenciales incluyen caracteres especiales, debe formatearlos de una manera que sea aceptable para curl según el shell que esté utilizando. Por ejemplo, puede insertar una barra diagonal inversa antes de cada carácter especial o ajustar toda la cadena de credenciales entre comillas dobles.

.Pasos
. En la interfaz de línea de comandos de la estación de trabajo local, ejecute el siguiente comando:
+
[source, curl]
----
curl --request GET \
"https://$FQDN_IP/api/cluster?fields=version" \
--user username:password
----
+
*ejemplo*

+
`curl --request GET "https://10.29.186.132/api/cluster?fields=version" --user admin:david123`



.Después de terminar
La información de la versión de ONTAP se muestra en formato JSON.
