---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog 
summary: Existen varias opciones disponibles para automatizar la puesta en marcha y administración de sus sistemas de almacenamiento de ONTAP. 
---
= Conozca las opciones de automatización de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varias opciones disponibles para automatizar la puesta en marcha y administración de sus sistemas de almacenamiento de ONTAP.



== API REST de ONTAP

A partir de ONTAP 9.6, ONTAP incluye una amplia API REST que proporciona la base para automatizar la puesta en marcha y la administración de sus sistemas de almacenamiento. Desde entonces, la API REST ha continuado expandiéndose y madurando. Ahora ofrece la opción preferida y estratégica al automatizar la administración de sus implementaciones de ONTAP.

.Acceso a la API de REST de forma nativa
Puede acceder a la API DE REST de ONTAP directamente desde cualquier lenguaje de programación que admita un cliente REST. Entre las opciones de idiomas populares se incluyen Python, PowerShell y Java.

.Migrando código ONTAPI heredado para utilizar REST
La API de ONTAPI (API Zephyr o ZAPI) es el conjunto original de llamadas exclusivas que incluye el software de NetApp ONTAP para dar cabida a la automatización de las tareas de administración y gestión del almacenamiento de datos. La API forma parte de link:../sw-tools/nmsdk.html["SDK de gestión de NetApp"]. Se espera que la interfaz de ONTAPI se deshabilite en futuras versiones de ONTAP. Si tiene código existente usando la API de ONTAPI, debe planificar la migración fuera de ONTAPI. NetApp ofrece soporte para convertir tu código y usar la nueva API de REST DE ONTAP. Consulte link:../migrate/ontapi_disablement.html["Migre desde ONTAPI a la API de REST"] si quiere más información.



== Kits de herramientas de software de cliente

NetApp ofrece kits de herramientas de cliente que abstraen la API DE REST DE ONTAP y facilitan la creación de código de automatización. Debe elegir uno apropiado para su lenguaje y entorno de desarrollo.

.Biblioteca de clientes de Python
La biblioteca de clientes Python es un paquete que puede utilizar al escribir scripts para acceder a la API DE REST de ONTAP. Proporciona compatibilidad con varios servicios subyacentes, incluidos la gestión de conexiones, el procesamiento de solicitudes asincrónicas y la gestión de excepciones. Al utilizar la biblioteca del cliente Python, puede desarrollar rápidamente código robusto para respaldar sus objetivos de automatización de ONTAP. Consulte link:../python/overview_pcl.html["Biblioteca de clientes de Python"] si quiere más información.

.Kit de herramientas de PowerShell
Es posible usar el kit de herramientas NetApp.ONTAP PowerShell para automatizar la administración de un clúster de ONTAP desde un host Windows. Consulte https://review.docs.netapp.com/us-en/ontap-automation_devnet-update/pstk/overview_pstk.html["Descripción general del kit de herramientas PowerShell"^] si quiere más información.



== Marcos de automatización

Puede crear e implementar código de automatización con uno de varios marcos

.Ansible
Asible es una herramienta de software de código abierto que permite el aprovisionamiento, la gestión de la configuración y la puesta en marcha de aplicaciones. Desde su lanzamiento y su posterior adquisición por RedHat, ha seguido creciendo en popularidad. NetApp proporciona módulos certificados con Ansible que pueden utilizar los clientes para automatizar la administración de sus sistemas de almacenamiento de ONTAP. Consulte link:../additional/learn_more.html["Leer más"] y.. https://www.netapp.com/devops-solutions/ansible/["Soluciones de DevOps de Ansible de NetApp"^] para obtener más información.

.Catálogo de automatización de BlueXP
La solución de NetApp https://console.bluexp.netapp.com/automationCatalog/["Catálogo de automatización de BlueXP"^] Está disponible a través de la interfaz de usuario web de BlueXP. El catálogo ofrece acceso a soluciones empaquetadas que pueden ayudarle a automatizar la implementación e integración de ONTAP con otros productos. Consulte https://docs.netapp.com/us-en/netapp-automation/["Automatización de NetApp"^] para documentación y más información.
