---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console, hub 
summary: Existen varias opciones disponibles para automatizar la puesta en marcha y administración de sus sistemas de almacenamiento de ONTAP. 
---
= Conozca las opciones de automatización de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varias opciones disponibles para automatizar la puesta en marcha y administración de sus sistemas de almacenamiento de ONTAP.



== API REST de ONTAP

A partir de ONTAP 9.6, ONTAP incluye una sólida API REST que proporciona la base para automatizar la implementación y la administración de sus sistemas de almacenamiento.  Desde entonces, la API REST ha seguido expandiéndose y madurando.  Ahora proporciona la opción preferida y estratégica al automatizar la administración de sus implementaciones de ONTAP .

.Acceso a la API de REST de forma nativa
Puede acceder a la API DE REST de ONTAP directamente desde cualquier lenguaje de programación que admita un cliente REST. Entre las opciones de idiomas populares se incluyen Python, PowerShell y Java.

.Migrando código ONTAPI heredado para utilizar REST
La API de ONTAPI (API de Zephyr o ZAPI) es el conjunto original de llamadas propietarias incluidas con el software NetApp ONTAP para respaldar la automatización de sus tareas de gestión y administración de almacenamiento de datos.  La API es parte de lalink:../sw-tools/learn-about-nmsdk.html["SDK de gestión de NetApp"] .  Si tiene un código existente que utiliza la API ONTAPI, debe planificar su migración a la API REST de ONTAP para aprovechar el conjunto ampliado de funciones disponible con la API REST.  NetApp brinda soporte para convertir su código para utilizar la API REST de ONTAP más nueva. Ver link:../migrate/migration-considerations.html["Migre desde ONTAPI a la API de REST"] Para más información.



== Kits de herramientas de software de cliente

NetApp ofrece kits de herramientas de cliente que abstraen la API DE REST DE ONTAP y facilitan la creación de código de automatización. Debe elegir uno apropiado para su lenguaje y entorno de desarrollo.

.Biblioteca de clientes de Python
La biblioteca de clientes Python es un paquete que puede utilizar al escribir scripts para acceder a la API DE REST de ONTAP. Proporciona compatibilidad con varios servicios subyacentes, incluidos la gestión de conexiones, el procesamiento de solicitudes asincrónicas y la gestión de excepciones. Al utilizar la biblioteca del cliente Python, puede desarrollar rápidamente código robusto para respaldar sus objetivos de automatización de ONTAP. Consulte link:../python/learn-about-pcl.html["Biblioteca de clientes de Python"] para obtener más información.

.Kit de herramientas de PowerShell
Es posible usar el kit de herramientas NetApp.ONTAP PowerShell para automatizar la administración de un clúster de ONTAP desde un host Windows. Consulte link:../pstk/learn-about-pstk.html["Obtenga más información sobre el kit de herramientas PowerShell de NetApp"] para obtener más información.



== Marcos de automatización

Puede crear e implementar código de automatización utilizando uno de varios marcos.

.Ansible
Asible es una herramienta de software de código abierto que permite el aprovisionamiento, la gestión de la configuración y la puesta en marcha de aplicaciones. Desde su lanzamiento y su posterior adquisición por RedHat, ha seguido creciendo en popularidad. NetApp proporciona módulos certificados con Ansible que pueden utilizar los clientes para automatizar la administración de sus sistemas de almacenamiento de ONTAP. Consulte link:../additional/learn_more.html["Leer más"] y.. https://www.netapp.com/devops-solutions/ansible/["Soluciones de DevOps de Ansible de NetApp"^] para obtener más información.

.Centro de automatización de la NetApp Console
El https://console.netapp.com/automationHub["Centro de automatización de la NetApp Console"^] Está disponible a través de la interfaz web de usuario de la consola. El centro de automatización proporciona acceso a soluciones empaquetadas que pueden ayudarle a automatizar la implementación e integración de ONTAP con otros productos. Ver https://docs.netapp.com/us-en/netapp-automation/["Automatización de NetApp"^] Para obtener documentación y más información.
