---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: rest, rest api, operation, request, response, crud 
summary: Mientras QUE REST establece un conjunto común de tecnologías y prácticas recomendadas, los detalles de cada API pueden variar en función de las opciones de diseño. 
---
= Características operativas de la API de REST DE ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mientras QUE REST establece un conjunto común de tecnologías y prácticas recomendadas, los detalles de cada API pueden variar en función de las opciones de diseño.



== Transacción de API de solicitud y respuesta

Cada llamada de API REST se realiza como una solicitud HTTP al sistema ONTAP, que genera una respuesta asociada al cliente. Este par de solicitud/respuesta se considera una transacción de API. Antes de utilizar la API, debería estar familiarizado con las variables de entrada disponibles para controlar una solicitud y el contenido de la salida de la respuesta.



== Compatibilidad con operaciones CRUD

Se accede a cada uno de los recursos disponibles a través de la API REST de ONTAP en función del modelo CRUD:

* Cree
* Lea
* Actualizar
* Eliminar


Para algunos de los recursos, solo se admite un subconjunto de las operaciones. Debe revisar la página de documentación de API de ONTAP en el clúster de ONTAP para obtener más información sobre cada recurso.



== Identificadores de objeto

A cada instancia u objeto de recurso se le asigna un identificador único cuando se crea. En la mayoría de los casos, el identificador es un UUID de 128 bits. Estos identificadores son únicos globalmente dentro de un clúster ONTAP específico. Después de emitir una llamada API que crea una nueva instancia de objeto, se devuelve una dirección URL con el valor de id asociado a la persona que llama en el encabezado de ubicación de la respuesta HTTP. Puede extraer el identificador y utilizarlo en llamadas posteriores cuando haga referencia a la instancia del recurso.


NOTE: El contenido y la estructura interna de los identificadores de objeto pueden cambiar en cualquier momento. Solo se deben usar los identificadores en las llamadas API aplicables según sea necesario cuando se hacen referencia a los objetos asociados.



== Instancias y colecciones de objetos

Dependiendo de la ruta de recursos y del método HTTP, una llamada API puede aplicarse a una instancia de objeto específica o a una colección de objetos.



== Operaciones síncronas y asíncronas

Hay dos maneras en que ONTAP realiza una solicitud HTTP recibida desde un cliente.

Procesamiento sincrónico:: ONTAP realiza la solicitud inmediatamente y responde con un código de estado HTTP de 200 o 201 si se realiza correctamente.
+
--
Cada solicitud que utilice los métodos GET, HEAD y OPTIONS se realiza siempre de forma síncrona. Además, las solicitudes que utilizan POST, PATCH y DELETE están diseñadas para ejecutarse de manera síncrona si se espera que se completen en menos de dos segundos.

--
Procesamiento asíncrono:: Si una solicitud asíncrona es válida, ONTAP crea una tarea en segundo plano para procesar la solicitud y un objeto de trabajo para anclar la tarea. El estado HTTP 202 se devuelve al llamante junto con el objeto de trabajo. Para determinar el éxito o fracaso final, debe recuperar el estado del trabajo.
+
--
Las solicitudes que utilizan los métodos POST, PATCH y DELETE están diseñadas para ejecutarse de manera asincrónica si se espera que tardan más de dos segundos en completarse.


NOTE: La `return_timeout` El parámetro de consulta está disponible con llamadas API asíncronas y puede convertir una llamada asíncrona a completado de forma síncrona. Consulte link:../rest/asynchronous_processing.html["Procesamiento asíncrono mediante el objeto Job"] si quiere más información.

--




== Seguridad

La seguridad proporcionada con la API DE REST se basa principalmente en las funciones de seguridad existentes disponibles con ONTAP. La API utiliza la siguiente seguridad:

Seguridad de la capa de transporte:: Todo el tráfico enviado a través de la red entre el cliente y el LIF de ONTAP se cifra normalmente con TLS, según los ajustes de configuración de ONTAP.
Autentificación de clientes:: Las mismas opciones de autenticación disponibles con ONTAP System Manager y el SDK de gestión de red también se pueden usar con la API de REST de ONTAP.
Autenticación HTTP:: En un nivel HTTP, por ejemplo, cuando se accede a la API de REST DE ONTAP directamente, hay dos opciones de autenticación como se describe a continuación. En cada caso, debe crear un encabezado de autorización HTTP e incluirlo con cada solicitud.
+
--
[cols="25,75"]
|===
| Opción | Descripción 


| Autenticación básica HTTP | El nombre de usuario y la contraseña de ONTAP se concatenan con dos puntos. La cadena se convierte a base64 y se incluye en la cabecera de solicitud. 


| OAuth 2,0 | A partir de ONTAP 9,14, puede solicitar un token de acceso desde un servidor de autorización externo e incluirlo como un token portador en el encabezado de la solicitud. 
|===
Para obtener más detalles sobre OAuth 2,0 y cómo se implementa en ONTAP, consulte https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["Descripción general de la implementación de ONTAP OAuth 2,0"^]. Consulte también link:../workflows/prepare_workflows.html["Prepárese para usar los flujos de trabajo"] abajo en este sitio.

--
Autorización de ONTAP:: ONTAP implementa un modelo de autorización basado en roles. La cuenta que utilice al acceder a la API DE REST de ONTAP o a la página de documentación de API deben tener la autoridad adecuada.

