---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords: rbac, role definitions, samples 
summary: La funcionalidad de control de acceso basado en roles de ONTAP se puede usar de diferentes maneras en función de su entorno. A continuación se presentan algunos escenarios comunes. En cada caso, el enfoque se centra en un objetivo específico de seguridad y administración con un ejemplo de la definición de función correspondiente. 
---
= Definiciones de rol de ejemplo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La funcionalidad de control de acceso basado en roles de ONTAP se puede usar de diferentes maneras en función de su entorno. A continuación se presentan algunos escenarios comunes. En cada caso, el enfoque se centra en un objetivo específico de seguridad y administración con un ejemplo de la definición de función correspondiente.


NOTE: Todos los ejemplos crean y modifican roles con `/api/security/roles` Y los extremos DE REST derivados. Para mayor claridad, cada uno de los comandos curl se refiere a un archivo de entrada JSON independiente.



== Limite el acceso a las operaciones de volumen de SVM

Puede que desee restringir la administración del volumen de almacenamiento dentro de una SVM. En el siguiente ejemplo, se ilustra esta función con una función que se crea primero y, a continuación, se actualiza opcionalmente.



=== Crear el rol inicial

Se crea un rol tradicional para permitir inicialmente el acceso a todas las funciones de administración de volúmenes principales, excepto el clonado. La función que se presenta a continuación se define con las siguientes características específicas:

* Es capaz de realizar todas las operaciones de volumen CRUD, incluidos Get, CREATE, Modify y DELETE
* No se puede crear un clon de volumen


.ejemplo de curl
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== Actualice el rol

El mismo rol puede modificarse para permitir al usuario también crear un clon de volumen.

.ejemplo de curl
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== Administración de la protección de datos

En determinadas situaciones, puede que desee ofrecer a un usuario funcionalidades de protección de datos limitadas. La función tradicional que se presenta a continuación se define con las siguientes características:

* Es posible crear y eliminar copias Snapshot, así como actualizar las relaciones de SnapMirror
* No se pueden crear ni modificar objetos de nivel superior como volúmenes o SVM


.ejemplo de curl
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== Generando informes de ONTAP

Puede crear un rol DE REST para proporcionar a los usuarios la capacidad de generar informes de ONTAP. La función que se presenta a continuación se define con las siguientes características:

* Se puede recuperar toda la información sobre objetos de almacenamiento relacionada con la capacidad y el rendimiento (como volumen, qtree, LUN, agregados, nodo, Y las relaciones de SnapMirror)
* No se pueden crear ni modificar objetos de nivel superior (como volúmenes o SVM).


.ejemplo de curl
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----