---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: Es posible gestionar la configuración de ONTAP EMS mediante la API DE REST. 
---
= Gestione notificaciones de eventos de EMS con la API DE REST de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la API DE REST de ONTAP para configurar la manera en que se envían notificaciones de eventos importantes del sistema de gestión de eventos (EMS), así como para recuperar todos los mensajes de EMS o mensajes específicos con ciertos atributos. Es posible utilizar la API DE REST para ayudar a automatizar tareas relacionadas con EMS, lo que ahorra tiempo sobre otros métodos de trabajo con mensajes de EMS.

Los siguientes ejemplos muestran cómo se puede utilizar la API DE REST de ONTAP para trabajar con mensajes EMS. En cada ejemplo, asegúrese de proporcionar sus valores para la información entre paréntesis <> donde se indique. También puede hacer referencia a una muestra https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Guión Python"^] Esto demuestra cómo automatizar una serie de actividades relacionadas con el EMS.



== Consulte los registros de eventos específicos

Con el `GET /support/ems/events` Llamada API, puede recuperar mensajes de eventos específicos, como el mensaje más reciente, los mensajes que contienen texto específico o los mensajes con una gravedad específica.

.Solicitud de ejemplo: Recupere el mensaje más reciente
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.Ejemplo de respuesta
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.Solicitud de ejemplo: Recupere un mensaje que contenga texto y gravedad específicos
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.Ejemplo de respuesta
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== Consulte la configuración de EMS existente

Con el `GET /support/ems/` Llamada API, es posible recuperar información acerca de la configuración de notificaciones de EMS existente.

.Ejemplo de solicitud
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.Ejemplo de respuesta
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== Cree una nueva configuración de notificación de EMS

Puede usar varias llamadas API junto para crear una nueva configuración de EMS para personalizar cómo y cuándo recibirá mensajes.

.Pasos
. Configure los ajustes del correo electrónico de todo el sistema. Por ejemplo:
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. Defina un filtro que utilice reglas específicas para coincidir con determinados mensajes. Por ejemplo:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. Cree un destino para los mensajes. Por ejemplo:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== API REST de ONTAP frente a comandos de la CLI de ONTAP

La API REST de ONTAP le permite automatizar flujos de trabajo con menos comandos que la interfaz de línea de comandos de ONTAP para muchas tareas. Por ejemplo, puede usar un único método POST API para crear un filtro, en lugar de utilizar varios comandos de la CLI. En la siguiente tabla se muestran los comandos de la CLI que sería necesario completar tareas EMS comunes en lugar de las llamadas API DE REST correspondientes:

|===
| API REST de ONTAP | CLI de ONTAP 


| `GET /support/ems` | `event config show` 


| `POST /support/ems/destinations`  a| 
. `event notification destination create`
. `event notification create`




| `GET /support/ems/events` | `event log show` 


| `POST /support/ems/filters`  a| 
. `event filter create -filter-name <filtername>`
. `event filter rule add -filter-name  <filtername>`


|===


== Información relacionada

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Ejemplo de script Python de la API REST de ONTAP"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["API DE REST de ONTAP: Automatice la notificación de eventos de alta gravedad"^]

